### ISSUE TITLE
Currency CHF not supported

### ISSUE THREAD

**Issue by jowitte** [gtg922r/obsidian-numerals#52] opened 2023-06-28 06:01 UTC
Minor issue. I tried "CHF" as a currency symbol for Swiss francs, but it's not supported. Is there a workaround?

**Comment by trippleflux** [comment] 2023-06-28 16:14
Also please add "IDR" for Indonesian Rupiahs.

**Comment by gtg922r** [comment] 2023-07-03 19:15
#54 created to support custom currencies rather than just a preset list which is how I'll handle additional currency types.

**Comment by gtg922r** [comment] 2023-07-03 19:16
Marking as dupe of #54

**Closed by gtg922r** 2023-07-03 19:16 UTC
Labels: duplicate
