### ISSUE TITLE
Line-breaks in formats other than "math"

### ISSUE THREAD

**Issue by Ra0R** [gtg922r/obsidian-numerals#12] opened 2022-11-22 13:12 UTC
In "math" format line breaks are done as expected:

![image](https://user-images.githubusercontent.com/22443382/203322391-cd21ddab-a612-416f-a500-d721fb082dfe.png)

For "math-highlight" or "math-tex" we get this:
![image](https://user-images.githubusercontent.com/22443382/203322468-8cf53048-3d31-4029-b8d1-cdafd79fa104.png)

Should probably be possible to set a width for the other formats aswell.

**Comment by gtg922r** [comment] 2022-11-24 07:23
Thanks, I can reproduce this for `math-tex`. I'll have to give some thought how to handle it. 

I can not reproduce this for `math-highlight` - are you sure that is affected as well?

Interestingly if you have a long line of mathjax in base obsidian using `$$` it overflows the margins too. 

Will have to experiment a bit.

**Comment by gtg922r** [comment] 2022-11-24 07:29
It doesn't seem to be as straightforward as I hoped with some simple CSS fixes. Also the underlying Mathjax [does not currently support automatic line break](https://docs.mathjax.org/en/latest/output/linebreaks.html) which would make this much easier. Will have to keep thinking abou tit

**Comment by Ra0R** [comment] 2022-11-25 10:37
Yes the issue seems to be present also for `math-highlight`:
![image](https://user-images.githubusercontent.com/22443382/203964451-94071e4f-cf38-4dab-9876-f8fb37ac5d47.png)

`
```math-highlight
# Points
points = 8pt + 9.8pt + 4pt + 6.6pt + 7.5pt + 5.5pt + 10pt

# Average
avg = points / 7
```
`

I did not look at the plugin code (and don't know much about Obsidian under the hood either). But MathJax seems to support rendering as HTML or SVG, could you not simply force the output to not overlapp the right-hand result pane? (E.g. in HTML by using something like `max-width: 70%`.

**Comment by gtg922r** [comment] 2022-11-26 07:01
Ahh, I was checking reader mode. I'm able to repro the math-highlight bug in live preview as well. Thanks, looking in to it

**Comment by gtg922r** [comment] 2022-11-26 08:32
Still broken for TeX, which might be harder to fix

**Comment by gtg922r** [comment] 2022-11-26 09:13
There doesn't seem to be  a straightforward solution to getting around the lack of MathJax support in v3 for automatic line breaks (I tried max width, forcing word-break, etc). 

It looks like [Release MathJax v4.0.0-alpha.1](https://github.com/mathjax/MathJax/releases/tag/4.0.0-alpha.1) does incorporate automatic line breaking. Once that gets pushed out, hopefully the devs will incorporate it in Obsidian, which should then fix it for Numerals. 

Going to mark this as won't fix. If its still broken if/when MathJax v4 is incorporated and Obsidian supports automatic line breaks natively, then can re-open

**Closed by gtg922r** 2022-11-26 09:13 UTC
Labels: bug

**Comment by gtg922r** [comment] 2022-11-26 09:23
For future reference, see this obsidian bug report: [Latex math newline line break \\ - Bug reports - Obsidian Forum](https://forum.obsidian.md/t/latex-math-newline-line-break/13321/3)
