### ISSUE TITLE
[Feature Request] Add feature to calculate total 

### ISSUE THREAD

**Issue by nazarhussain** [gtg922r/obsidian-numerals#36] opened 2023-03-13 13:33 UTC
I had been using this plugin in Obsidian to primarily replace my usage of `Numi` app. It would be really nice if you can add a feature like `TOTAL` function in `Numi` which actually sum up all the evaluations above. 

```
Coffe: 2,4 -> 2,4
Bread: 2,8 -> 2,8
= TOTAL -> 5,2
```

This will be so helpful and hope it's easy to implement.

**Comment by jemgold** [comment] 2023-03-17 18:09
yes! would love this

**Comment by ChristinWhite** [comment] 2023-03-20 06:29
I believe this is a duplicate of #18, there’s some discussion about syntax there so additional feedback might be useful.

**Comment by Stakker** [comment] 2023-05-30 09:45
I'm also missing this feature very much, but I wrote my comment in the duplicate issue mentioned above :-)

**Comment by gtg922r** [comment] 2024-03-01 18:41
This is now live in [Numerals 1.4 (Beta)](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.4.0)

Would really appreciate beta testing and feedback prior to me pushing this out as a full release! Please see the instructions on the README for how to use BRAT to beta test!

**Comment by nazarhussain** [comment] 2024-03-01 19:06
> This is now live in [Numerals 1.4 (Beta)](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.4.0)

That works like a charm!

**Comment by gtg922r** [comment] 2024-06-12 06:56
Closing with public release of [Numerals 1.5](https://github.com/gtg922r/obsidian-numerals/releases/tag/1.5.0)

**Closed by gtg922r** 2024-06-12 06:56 UTC
Labels: enhancement, release

**Comment by vaygr** [comment] 2025-11-23 01:58
@gtg922r I think it would be nice to have an option to display total regardless of blank lines / comments. Do you think it's feasible to implement?
