### ISSUE TITLE
The equalization and calculation does not work

### ISSUE THREAD

**Issue by Wismut83** [gtg922r/obsidian-numerals#29] opened 2023-02-08 13:36 UTC
![exaple](https://i.imgur.com/ttfLLeD.jpeg)

**Comment by gtg922r** [comment] 2023-02-08 17:37
Odd. I'm unable to reproduce. Can you please share the raw text?

**Comment by Wismut83** [comment] 2023-02-09 15:08
I also disabled all third-party plugins to get the result. It didn't help.
[test.md](https://github.com/gtg922r/obsidian-numerals/files/10698520/test.md)

**Comment by gtg922r** [comment] 2023-02-14 07:02
Thanks for sharing the raw markdown, it helped me locate the bug. Its an issue with how strings are being located for different locales, and how that is handled by the underlying math library. 

This is a duplicate of #23, so I'm going to close this one as dupe

**Closed by gtg922r** 2023-02-14 07:02 UTC
Labels: bug, question

**Comment by Wismut83** [comment] 2023-02-14 10:38
I created a new database, added all my extensions, and everything worked in the new database. But TexStyle is still displayed as in the picture above.
